### ISSUE TITLE
How to intergrate this to calibre-web

### ISSUE THREAD

**Issue by graven04** [Timmy-B/calibre-web-DarkReader#1]
Well the issues is just the title. I have very little coding knowledge and i have no idea how i will use this in my calibre web server. Which files do i replace if i have to replace any at all? But very good project though i was waiting for this for a long time.

**Comment by Timmy-B** [comment]
While it is working, I uploaded this rather hastily and need to figure out the easiest way to add the mod. which Im working on now.
![image](https://user-images.githubusercontent.com/14361551/145680381-06badc84-7250-4688-98bc-5500a133955f.png)

**Comment by graven04** [comment]
By appending this on the main.css file it works. However, the text is still black (please fix this) but otherwise it looks exactly like your picture.
